#  Copyright (c) 2012-2019, GLP Schweiz. This file is part of
#  hitobito_glp and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_glp.


# Settings relevant for the hitobito_glp wagon
# Overrides settings from the main application
application:
  languages:
    de: Deutsch
    en: English
    fr: Fran√ßais
    it: Italiano
list_domain: grunliberale.ch

# The person with this email has root access to everything
# This person should only be used by the operators of the application,
# not the customers.
# Initially, a password reset token may be mailed from the application
# to this address to set a password.
root_email: hitobito-glp@grunliberale.ch

impersonate:
  notify: false

two_factor_skip:
  - '@puzzle.ch'

people:
  abos: true

table_displays: false
